language: python
env:
  - TOXENV=pep8
  - TOXENV=py3
install: pip install -U tox
# SYS_PTRACE capability is not available in default containers,
# use sudo to work around the issue:
# https://github.com/travis-ci/travis-ci/issues/9033
sudo: required
script: tox
